sudo: false
language: scala
scala:
  - 2.11.12
  - 2.12.4
  - 2.13.0-M2
jdk:
  - oraclejdk8
env:
  - TRAVIS_NODE_VERSION="7.10.1" SCALAJS_VERSION="0.6.22"
  - TRAVIS_NODE_VERSION="7.10.1" SCALAJS_VERSION="1.0.0-M3"
  - TRAVIS_NODE_VERSION="8.9.1" SCALAJS_VERSION="0.6.22"
  - TRAVIS_NODE_VERSION="8.9.1" SCALAJS_VERSION="1.0.0-M3"
  - TRAVIS_NODE_VERSION="9.2.0" SCALAJS_VERSION="0.6.22"
  - TRAVIS_NODE_VERSION="9.2.0" SCALAJS_VERSION="1.0.0-M3"
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install
script:
  - sbt -Djava.locale.providers=CLDR ++$TRAVIS_SCALA_VERSION macroUtils/publishLocal
  - sbt -Djava.locale.providers=CLDR ++$TRAVIS_SCALA_VERSION coreJS/scalastyle testSuiteJVM/scalastyle testSuiteJVM/test:scalastyle testSuiteJS/scalastyle testSuiteJS/test:scalastyle coreNative/scalastyle coreJVM/scalastyle
  - if [[ $TRAVIS_SCALA_VERSION == "2.11.11" ]]; then sbt ++$TRAVIS_SCALA_VERSION coreNative/compile; fi;
  - sbt -Djava.locale.providers=CLDR ++$TRAVIS_SCALA_VERSION testSuiteJVM/test
  - sbt -Djava.locale.providers=CLDR ++$TRAVIS_SCALA_VERSION '; set scalaJSStage in Global := FullOptStage' testSuiteJS/test
  # Tricks to avoid unnecessary cache updates, from
  # http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
